<!DOCTYPE html>
<html lang="en-IN">
<head>
    <meta charset="utf-8">
    <title>{{ $title ?? 'Payslip Generator' }}</title>
    <style>
        @page { margin: 18mm 16mm; }
        body { font: 11pt/1.45 DejaVu Sans, sans-serif; color: #16181d; }
        .doc__masthead { border-bottom: 2px solid #16181d; padding-bottom: 8pt; margin-bottom: 14pt; }
        .doc__company { font-size: 14pt; font-weight: 700; margin: 0; }
        .doc__meta { color: #5d636e; font-size: 9pt; margin: 2pt 0 0; }
        .doc__title { font-size: 12pt; margin: 0 0 10pt; text-transform: uppercase; letter-spacing: .04em; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 4pt 0; border-bottom: .5pt solid #d9dde4; text-align: left; vertical-align: top; }
        td.amount { text-align: right; font-variant-numeric: tabular-nums; }
        .doc__working { margin-top: 14pt; font-size: 9pt; color: #3d434e; }
        .doc__citations { margin-top: 10pt; font-size: 8pt; color: #5d636e; }
        .doc__footer { margin-top: 18pt; font-size: 8pt; color: #5d636e; border-top: .5pt solid #d9dde4; padding-top: 6pt; }
    </style>
</head>
<body>

<div class="doc__masthead">
    @if (!empty($company['logo']))
        <img src="{{ $company['logo'] }}" alt="" height="40">
    @endif
    <p class="doc__company">{{ $company['name'] ?? '' }}</p>
    <p class="doc__meta">
        {{ $company['address'] ?? '' }}
        @if (!empty($company['gstin'])) · GSTIN {{ $company['gstin'] }} @endif
        @if (!empty($company['pan'])) · PAN {{ $company['pan'] }} @endif
    </p>
</div>

<h1 class="doc__title">{{ $title ?? 'Payslip Generator' }}</h1>

<table>
    <tbody>
    @foreach ($data as $key => $value)
        @continue(is_array($value) || str_ends_with((string) $key, '_formatted'))
        <tr>
            <th scope="row">{{ ucfirst(str_replace('_', ' ', (string) $key)) }}</th>
            <td class="amount">{{ $data[$key.'_formatted'] ?? (is_bool($value) ? ($value ? 'Yes' : 'No') : $value) }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

@if (count($result->steps()))
    <div class="doc__working">
        <strong>How this was worked out</strong>
        <table>
            <tbody>
            @foreach ($result->steps() as $step)
                <tr>
                    <th scope="row">{{ $step->label }}@if ($step->formula)<br><small>{{ $step->formula }}</small>@endif</th>
                    <td class="amount">{{ $step->amount?->format() }}</td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endif

@if (count($result->citations()))
    <div class="doc__citations">
        @foreach ($result->citations() as $citation)
            <div>{{ $citation }}</div>
        @endforeach
    </div>
@endif

<div class="doc__footer">
    Generated by Payslip Generator (crmleaf/payslip-generator). This is a computer-generated document.
    Payment of Wages Act 1936, section 13A and the Code on Wages 2019 - the particulars a wage slip must carry - with EPF, ESI and professional tax deducted per their own enactments.
</div>

</body>
</html>
